language: java
jdk:
  - oraclejdk8
script:
  - ant build
  - ant compile.module.cmsc167_testing.tests
notifications:
  email:
    recipients:
      - abcdefghijklm400@gmail.com
      - ruffamaefamat@gmail.com
    on_success: always
    on_failure: always
