language: java
jdk:
  - oraclejdk8
before_install:
  cd C:\Program Files\Java
script:
  - ant build
  - ant test
notifications:
  email:
    recipients:
      - abcdefghijklm400@gmail.com
      - ruffamaefamat@gmail.com
    on_success: always
    on_failure: always
