language: java
jdk:
  - oraclejdk8
script:
  - ant build
  - ant test
before_install:
  cd java
notifications:
  email:
    recipients:
      - abcdefghijklm400@gmail.com
      - ruffamaefamat@gmail.com
    on_success: always
    on_failure: always
